services:
  webdav:
    build: .
    container_name: webdav-server
    ports:
      - "0.0.0.0:4918:4918"
    volumes:
      # TODO change this
      - ./path/to/data:/data
    environment:
      # Runtime
      - WEBDAV_DATABASE=/data/notes.db
      - WEBDAV_PORT=4918

      # TODO populate .env file
      # Credentials
      - WEBDAV_USERNAME=${WEBDAV_USERNAME}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD}
      - WEBDAV_USER_ID=${WEBDAV_USER_ID}
    restart: unless-stopped

